// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhavocnyyzziqvtyocyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5oYXZvY255eXp6aXF2dHlvY3lqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNzk4OTQsImV4cCI6MjA2NTc1NTg5NH0.PCC6C60fIXMIKibCnw3j7i7s5D0-U6b3_aTmSN8qiR8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);